PROJECT_DIR : '/Users/A/PycharmProjects/computer_vision_project/digit_reco'
optimizer : 'adam'
loss : 'sparse_categorical_crossentropy'
metrics : 'accuracy'
batch_size : 200
epoch : 10
SaveModelDir : 'C:\Users\A\PycharmProjects\computer_vision_project\SaveModels\'
wanted_model : '2023_05_29_11_21_05'
SaveImageDir : 'C:\Users\A\PycharmProjects\computer_vision_project\SaveImages\'
num_classes : 10
